### PR TITLE
don't block writes after session has shut down

### PR DESCRIPTION
**Pull request by whyrusleeping**
This should address the issues in #45 . I've applied this to my machine thats been able to semi-reliably reproduce the issue, so we'll see if it crops up again.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
So far the issue hasnt come up again while running this code. Still watching...

**Comment by whyrusleeping** [comment]
Mmmm, thats interesting. Manages to get things hanging still even with this patch. I'll investigate more.

**Comment by evanphx** [comment]
Given the age, I'm going to go ahead and close this PR.

**Comment by evanphx** [comment]
@whyrusleeping it's been a sec, but I do see where you're going with this.

**Pull request closed without merging**
