### PR TITLE
properly handle closing streams before they are ACKed

### PR DESCRIPTION
**Pull request by whyrusleeping**
Should address bug #26. The issue occurs when opening unidirectional streams then closing them quickly before the other side can ACK the open.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
After further testing I can still reproduce the bug (though it requires far more effort) in ipfs. In the small reproduction program posted in the tracking issue I cannot get a repro.

**Comment by whyrusleeping** [comment]
Alright, got it figured out properly. Ready for review

**Comment by whyrusleeping** [comment]
one potential issue is that this can still lock up if one side doesnt have the fix. (since they won't ACK correctly). This could be addressed either by requiring everyone to use the correct version, or maybe by adding a timeout to that select case in session.go:149

**Comment by slackpad** [comment]
Hi @whyrusleeping thanks for the PR and sorry for the delay - finally had a little time to go through this in some detail. I think there should be a way to do this completely on the sender side without relying on the other party sending an ACK to clear the semaphore. I'll work up a change based on your PR and post it here shortly.

**Comment by whyrusleeping** [comment]
@slackpad thanks for getting that in. Not relying on the other side to be correct is definitely a better solution.

**Pull request merged**
